# คำศัพท์ภาษาอังกฤษ -> ไทย สำหรับหน้าจอบัญชี
# ใช้คำเดียวกับคำแปล Odoo ที่ผู้ใช้เห็นอยู่แล้ว (พาร์ทเนอร์, สมุดบันทึก, ลงรายการ)
# ชื่อยี่ห้อ/ศัพท์เทคนิค (PDF, API, Stripe, Peppol ฯลฯ) ไม่แปล
# เพิ่มคำใหม่ได้ที่นี่ แล้วอัปเกรดโมดูล npd_th_labels


def norm(text):
    return ' '.join((text or '').split())


_RAW = {
    # --- ทั่วไป ---
    'Active': 'ใช้งาน',
    'All': 'ทั้งหมด',
    'Alert': 'แจ้งเตือน',
    'Amount': 'จำนวนเงิน',
    'Approve': 'อนุมัติ',
    'Archived': 'เก็บถาวร',
    'Not archived': 'ไม่เก็บถาวร',
    'Average': 'ค่าเฉลี่ย',
    'Balance': 'ยอดคงเหลือ',
    'Bank': 'ธนาคาร',
    'Bank Account': 'บัญชีธนาคาร',
    'Bank Transfer': 'โอนเงินผ่านธนาคาร',
    'Barcode': 'บาร์โค้ด',
    'Barcode Height': 'ความสูงบาร์โค้ด',
    'Barcode Type': 'ชนิดบาร์โค้ด',
    'Barcode Width': 'ความกว้างบาร์โค้ด',
    'Branch': 'สาขา',
    'Branch Name': 'ชื่อสาขา',
    'Is Branch': 'เป็นสาขา',
    'Calendar Year': 'ปีปฏิทิน',
    'Cancel': 'ยกเลิก',
    'Canceled': 'ยกเลิกแล้ว',
    'Cancelled': 'ยกเลิกแล้ว',
    'Cash': 'เงินสด',
    'Close': 'ปิด',
    'Code': 'รหัส',
    'Color': 'สี',
    'Columns': 'คอลัมน์',
    'Company': 'บริษัท',
    'Company Currency': 'สกุลเงินบริษัท',
    'Company Field': 'ฟิลด์บริษัท',
    'Company Tax ID': 'เลขประจำตัวผู้เสียภาษีของบริษัท',
    'Main Company': 'บริษัทหลัก',
    'Name Company': 'ชื่อบริษัท',
    'Multiple companies': 'หลายบริษัท',
    'Allowed companies': 'บริษัทที่อนุญาต',
    'Allowed company': 'บริษัทที่อนุญาต',
    'Effective companies': 'บริษัทที่มีผล',
    'Configurations': 'การตั้งค่า',
    'Confirm': 'ยืนยัน',
    'Confirmed': 'ยืนยันแล้ว',
    'Create by': 'สร้างโดย',
    'Credit Card': 'บัตรเครดิต',
    'Currency': 'สกุลเงิน',
    'Foreign Currency': 'สกุลเงินต่างประเทศ',
    'Expected Currency Rate': 'อัตราแลกเปลี่ยนที่คาดไว้',
    'Customer': 'ลูกค้า',
    'Supplier': 'ผู้ขาย',
    'Vendor': 'ผู้ขาย',
    'Date': 'วันที่',
    'Date At': 'ณ วันที่',
    'Date Field': 'ฟิลด์วันที่',
    'Date From': 'ตั้งแต่วันที่',
    'Date To': 'ถึงวันที่',
    'Date range': 'ช่วงวันที่',
    'Date Range': 'ช่วงวันที่',
    'Date is Readonly': 'แก้ไขวันที่ไม่ได้',
    'DateWise Report': 'รายงานตามวันที่',
    'Doc Date': 'วันที่เอกสาร',
    'Due Date': 'วันครบกำหนด',
    'Effective Date': 'วันที่มีผล',
    'End Date': 'วันที่สิ้นสุด',
    'End date': 'วันที่สิ้นสุด',
    'Start Date': 'วันที่เริ่มต้น',
    'Start date': 'วันที่เริ่มต้น',
    'Request Date': 'วันที่ขอ',
    'Base date': 'วันที่ตั้งต้น',
    'Pivot Date': 'วันที่อ้างอิง',
    'Show Pivot Date': 'แสดงวันที่อ้างอิง',
    'Today': 'วันนี้',
    'Days': 'วัน',
    'Month': 'เดือน',
    'Quarter': 'ไตรมาส',
    'Period': 'งวด',
    'Periods': 'งวด',
    'Previous Period': 'งวดก่อน',
    'Report Period': 'งวดรายงาน',
    'Fy Start Date': 'วันเริ่มปีบัญชี',
    'Default': 'ค่าเริ่มต้น',
    'Department': 'แผนก',
    'Description': 'รายละเอียด',
    'Detail': 'รายละเอียด',
    'Detailed': 'แบบละเอียด',
    'Very Detailed': 'ละเอียดมาก',
    'Difference': 'ผลต่าง',
    'Disabled': 'ปิดใช้งาน',
    'Discount': 'ส่วนลด',
    'Discount Type': 'ประเภทส่วนลด',
    'Product Discount': 'ส่วนลดสินค้า',
    'Domain': 'เงื่อนไข',
    'Done': 'เสร็จสิ้น',
    'Draft': 'ร่าง',
    'Set to Draft': 'กลับเป็นร่าง',
    'Reset To Draft': 'กลับเป็นร่าง',
    'Skip Draft State': 'ข้ามสถานะร่าง',
    'Email': 'อีเมล',
    'Email ID': 'อีเมล',
    'Electronic mail': 'อีเมล',
    'Employee': 'พนักงาน',
    'Error': 'ข้อผิดพลาด',
    'Export': 'ส่งออก',
    'Export Excel': 'ส่งออก Excel',
    'Export PDF': 'ส่งออก PDF',
    'Export TXT': 'ส่งออก TXT',
    'Export XLSX': 'ส่งออก XLSX',
    'False': 'ไม่ใช่',
    'True': 'ใช่',
    'Filters': 'ตัวกรอง',
    'Additional Filtering': 'ตัวกรองเพิ่มเติม',
    'Show filters box': 'แสดงกล่องตัวกรอง',
    'Filter box search view': 'มุมมองค้นหาของกล่องตัวกรอง',
    'Fixed': 'คงที่',
    'Format': 'รูปแบบ',
    'From': 'จาก',
    'From (computed)': 'จาก (คำนวณ)',
    'To': 'ถึง',
    'To (computed)': 'ถึง (คำนวณ)',
    'Generate Report': 'สร้างรายงาน',
    'Group By': 'จัดกลุ่มตาม',
    'Grouped By': 'จัดกลุ่มตาม',
    'No group': 'ไม่จัดกลุ่ม',
    'Image': 'รูปภาพ',
    'Label': 'ป้ายกำกับ',
    'Label Text Limit': 'จำกัดความยาวป้ายกำกับ',
    'Layout': 'รูปแบบการจัดหน้า',
    'Levels': 'ระดับ',
    'Line': 'รายการ',
    'Max': 'สูงสุด',
    'Min': 'ต่ำสุด',
    'Model': 'โมเดล',
    'Name': 'ชื่อ',
    'None': 'ไม่มี',
    'Normal': 'ปกติ',
    'Note': 'หมายเหตุ',
    'Notes': 'หมายเหตุ',
    'Number': 'เลขที่',
    'Next Number': 'เลขถัดไป',
    'Numeric': 'ตัวเลข',
    'Objective': 'วัตถุประสงค์',
    'Options': 'ตัวเลือก',
    'Other': 'อื่นๆ',
    'Overdue': 'เกินกำหนด',
    'Percent': 'เปอร์เซ็นต์',
    'Percentage': 'เปอร์เซ็นต์',
    'Percentage of Price': 'เปอร์เซ็นต์ของราคา',
    'Planned': 'ตามแผน',
    'Please make sure that this is a wanted behavior.': 'กรุณาตรวจสอบว่าเป็นไปตามที่ต้องการ',
    'Warning:': 'คำเตือน:',
    'Prefix': 'คำนำหน้า',
    'Suffix': 'คำต่อท้าย',
    'Preview': 'ดูตัวอย่าง',
    'Print': 'พิมพ์',
    'Product': 'สินค้า',
    'Quantity': 'จำนวน',
    'Unit Price': 'ราคาต่อหน่วย',
    'Purchase Unit': 'หน่วยซื้อ',
    'Ref': 'อ้างอิง',
    'Reference': 'อ้างอิง',
    'References': 'อ้างอิง',
    'Remaining': 'คงเหลือ',
    'Report': 'รายงาน',
    'Report File': 'ไฟล์รายงาน',
    'Report File Name': 'ชื่อไฟล์รายงาน',
    'Rounding': 'การปัดเศษ',
    'Save': 'บันทึก',
    'Sequence': 'ลำดับ',
    'sequence': 'ลำดับ',
    'Serial Number': 'หมายเลขซีเรียล',
    'Serial Number Settings': 'ตั้งค่าหมายเลขซีเรียล',
    'Source': 'แหล่งข้อมูล',
    'Split': 'แยก',
    'Standard': 'มาตรฐาน',
    'State': 'สถานะ',
    'Status': 'สถานะ',
    'Show state': 'แสดงสถานะ',
    'Sub-Status': 'สถานะย่อย',
    'String': 'ข้อความ',
    'Submit': 'ส่ง',
    'Sum': 'ผลรวม',
    'Summary': 'สรุป',
    'Display Summary': 'แสดงสรุป',
    'Template': 'แม่แบบ',
    'Temporary': 'ชั่วคราว',
    'Total': 'รวม',
    'Total Amount': 'ยอดรวม',
    'Type': 'ประเภท',
    'Valid': 'ใช้ได้',
    'Validate': 'ยืนยัน',
    'Value type': 'ชนิดค่า',
    'View': 'ดูรายงาน',
    'Visibility': 'การแสดงผล',
    'Widget': 'วิดเจ็ต',
    'Waiting to Approved': 'รออนุมัติ',
    'Verify By': 'ตรวจสอบโดย',
    'or': 'หรือ',
    'in': 'ใน',
    'Expression': 'สูตร',
    'Factor': 'ตัวคูณ',
    'Legal Form': 'รูปแบบนิติบุคคล',
    'First name': 'ชื่อ',
    'Last name': 'นามสกุล',
    'Firstname Lastname': 'ชื่อ นามสกุล',
    'Lastname Firstname': 'นามสกุล ชื่อ',
    'Lastname, Firstname': 'นามสกุล, ชื่อ',
    'Form Has Lastname First': 'ฟอร์มแสดงนามสกุลก่อน',
    'No Space Title and Name': 'ไม่เว้นวรรคระหว่างคำนำหน้ากับชื่อ',
    'Partner Names Order': 'ลำดับชื่อพาร์ทเนอร์',
    'Partner Names Order Changed': 'เปลี่ยนลำดับชื่อพาร์ทเนอร์แล้ว',
    'Recalculate names': 'คำนวณชื่อใหม่',
    '100 words': '100 คำ',
    '150 words': '150 คำ',
    '200 words': '200 คำ',
    '50 words': '50 คำ',
    'Fetched fields name': 'ชื่อฟิลด์ที่ดึงมา',
    'Fields to fetch': 'ฟิลด์ที่ต้องดึง',
    'Show settings button': 'แสดงปุ่มตั้งค่า',
    'Add to dashboard': 'เพิ่มในแดชบอร์ด',
    'Enable Zooming': 'เปิดการซูม',
    'Enable Zooming for charts': 'เปิดการซูมกราฟ',
    'Toggle Color': 'สลับสี',
    'Open report in wide mode by default': 'เปิดรายงานแบบเต็มความกว้างเป็นค่าเริ่มต้น',
    'Headers/Footers': 'หัวกระดาษ/ท้ายกระดาษ',
    'Landscape PDF': 'PDF แนวนอน',
    'QR/Barcode Configuration': 'ตั้งค่า QR/บาร์โค้ด',
    'Basic Receipt': 'ใบเสร็จแบบพื้นฐาน',
    'Incoterm': 'เงื่อนไขการส่งมอบ (Incoterm)',
    'Fiscal Position': 'สถานะทางการเงิน',
    'Pro-forma': 'ใบแจ้งหนี้ล่วงหน้า',
    'Re-Invoice Costs': 'เรียกเก็บค่าใช้จ่ายกับลูกค้า',
    'Average Cost (AVCO)': 'ต้นทุนถัวเฉลี่ย (AVCO)',
    'First In First Out (FIFO)': 'เข้าก่อนออกก่อน (FIFO)',
    'Closing Entry by product': 'บันทึกปิดบัญชีแยกตามสินค้า',
    'Partner Salesperson': 'พนักงานขายของพาร์ทเนอร์',

    # --- พาร์ทเนอร์/บัญชีธนาคาร ---
    'Partner': 'พาร์ทเนอร์',
    'Partners': 'พาร์ทเนอร์',
    'Filter partners': 'กรองพาร์ทเนอร์',
    'Show Partner Details': 'แสดงรายละเอียดพาร์ทเนอร์',
    'Duplicate Bank Partner': 'พาร์ทเนอร์ที่ใช้บัญชีธนาคารซ้ำ',
    'Partners with same bank': 'พาร์ทเนอร์ที่ใช้บัญชีธนาคารเดียวกัน',
    'One or more Bank Accounts set on this partner are also used by others:': 'บัญชีธนาคารของพาร์ทเนอร์นี้ถูกใช้กับพาร์ทเนอร์อื่นด้วย:',
    'Payee': 'ผู้รับเงิน',

    # --- สมุดบันทึก/รายการบัญชี ---
    'Account': 'บัญชี',
    'Account Code From': 'รหัสบัญชีตั้งแต่',
    'Account Code To': 'รหัสบัญชีถึง',
    'From Code': 'จากรหัส',
    'Filter accounts': 'กรองบัญชี',
    'With Account Name': 'แสดงชื่อบัญชี',
    'Analytic Account': 'บัญชีวิเคราะห์',
    'Show Analytic Account': 'แสดงบัญชีวิเคราะห์',
    'Analytic Distribution': 'การกระจายบัญชีวิเคราะห์',
    'Analytic Domain': 'เงื่อนไขบัญชีวิเคราะห์',
    'Journal': 'สมุดบันทึก',
    'Journals': 'สมุดบันทึก',
    'Journal Entry': 'รายการบันทึกบัญชี',
    'Journal Item': 'รายการบันทึก',
    'Journal Items Domain': 'เงื่อนไขรายการบันทึก',
    'Move': 'รายการบันทึกบัญชี',
    'Move Entry': 'รายการบันทึกบัญชี',
    'View Move': 'ดูรายการบันทึกบัญชี',
    'Create Move': 'สร้างรายการบันทึกบัญชี',
    'Delete/Reverse Move': 'ลบ/กลับรายการบันทึกบัญชี',
    'Allow Reversal of journal entries': 'อนุญาตให้กลับรายการบันทึกบัญชี',
    'Show Move Line Details': 'แสดงรายละเอียดรายการบันทึก',
    'Move Lines Source': 'แหล่งรายการบันทึก',
    'Move lines source': 'แหล่งรายการบันทึก',
    'Entry number': 'เลขที่รายการ',
    'Entry Sequence': 'ลำดับเลขรายการ',
    'Numbered by Journal Sequence': 'รันเลขตามลำดับของสมุดบันทึก',
    'Show Auto Sequence': 'แสดงการรันเลขอัตโนมัติ',
    'Refund Sequence': 'แยกลำดับเลขใบลดหนี้',
    'Credit Note Entry Sequence': 'ลำดับเลขใบลดหนี้',
    'Credit Notes Next Number': 'เลขถัดไปของใบลดหนี้',
    'Post': 'ลงรายการ',
    'Posted': 'ลงรายการแล้ว',
    'Not Posted': 'ยังไม่ลงรายการ',
    'Unposted Amount': 'ยอดที่ยังไม่ลงรายการ',
    'All Entries': 'รายการทั้งหมด',
    'All Posted Entries': 'เฉพาะรายการที่ลงรายการแล้ว',
    'Target Moves': 'สถานะรายการ',
    'Move Target': 'สถานะรายการ',
    'Payable': 'เจ้าหนี้',
    'Receivable': 'ลูกหนี้',
    'Payable Accounts Only': 'เฉพาะบัญชีเจ้าหนี้',
    'Receivable Accounts Only': 'เฉพาะบัญชีลูกหนี้',
    'AP': 'เจ้าหนี้',
    'AR': 'ลูกหนี้',
    'Sale': 'ขาย',
    'Sales': 'การขาย',
    'Purchase': 'ซื้อ',
    'Sale/Purchase': 'ขาย/ซื้อ',
    'Sale Type': 'ประเภทการขาย',
    'Transfer': 'โอน',
    'Is Transfer': 'เป็นการโอน',
    'Can Transfer': 'โอนได้',
    'Transferable': 'โอนได้',
    'Transfer Journal': 'สมุดบันทึกการโอน',
    'Write Off': 'ตัดยอด',
    'Write-off Account': 'บัญชีตัดยอด',
    'Initial Balance Entry': 'รายการยอดยกมา',
    'Only One Unaffected Earnings Account': 'มีบัญชีกำไรสะสมที่ยังไม่จัดสรรได้บัญชีเดียว',
    'Communication': 'ข้อความอ้างอิง',
    'Memo': 'บันทึกย่อ',

    # --- ใบแจ้งหนี้/บิล ---
    'Invoice': 'ใบแจ้งหนี้',
    'Invoice Date': 'วันที่ใบแจ้งหนี้',
    'Invoice Number': 'เลขที่ใบแจ้งหนี้',
    'Invoice Tax': 'ภาษีใบแจ้งหนี้',
    'Customer Invoice': 'ใบแจ้งหนี้ลูกค้า',
    'Customer Invoice Number': 'เลขที่ใบแจ้งหนี้ลูกค้า',
    'Sale Invoice': 'ใบแจ้งหนี้ขาย',
    'Available Invoices': 'ใบแจ้งหนี้ที่เลือกได้',
    'Bill Date': 'วันที่บิล',
    'Bill Information': 'ข้อมูลบิล',
    'Bill Reference': 'เลขอ้างอิงบิล',
    'Gross Amount': 'ยอดรวมก่อนหัก',
    'Net Amount': 'ยอดสุทธิ',
    'UnTaxed Amount': 'ยอดก่อนภาษี',
    'Residual Amount': 'ยอดคงค้าง',
    'Receipt': 'ใบเสร็จรับเงิน',
    'Has Zero Amount Receipt': 'มีใบเสร็จยอดเป็นศูนย์',
    'Receipt Condition Count': 'จำนวนใบเสร็จตามเงื่อนไข',
    'Receipt Correction Count': 'จำนวนใบเสร็จที่แก้ไข',
    'Purchase Matching': 'จับคู่ใบสั่งซื้อ',
    'Is Purchase Matched': 'จับคู่ใบสั่งซื้อแล้ว',
    'Purchase Order Name': 'เลขที่ใบสั่งซื้อ',
    'Purchase Request': 'ใบขอซื้อ',
    'Purchase Month': 'เดือนที่ซื้อ',
    'Insurance Deposit Product': 'สินค้าเงินประกัน',
    'Can be Rent': 'ให้เช่าได้',
    'Rent': 'เช่า',
    'Quantity Rent': 'จำนวนที่เช่า',
    'Day of Rent': 'จำนวนวันเช่า',
    'Rental Discount': 'ส่วนลดค่าเช่า',
    '- Rental Discount': '- ส่วนลดค่าเช่า',
    'Can Confirm/Cancel': 'ยืนยัน/ยกเลิกได้',
    'Can Edit Head Office Branch': 'แก้ไขสาขาสำนักงานใหญ่ได้',

    # --- รับ/จ่ายชำระ ---
    'Payment': 'การชำระเงิน',
    'payment': 'การชำระเงิน',
    'Payments': 'การชำระเงิน',
    'Paid': 'ชำระแล้ว',
    'paid': 'ชำระแล้ว',
    'Paid Total': 'ยอดชำระรวม',
    'Payment Total': 'ยอดชำระรวม',
    'Amount to Pay': 'ยอดที่ต้องชำระ',
    'Payment Date': 'วันที่ชำระ',
    'Payment Name': 'เลขที่การชำระ',
    'Payment Memo': 'บันทึกย่อการชำระ',
    'Payment Information': 'ข้อมูลการชำระเงิน',
    'Payment Method': 'วิธีการชำระเงิน',
    'Payment method': 'วิธีการชำระเงิน',
    'Payment Method Clear': 'วิธีการชำระ (เคลียร์)',
    'Payment Multi': 'ชำระหลายรายการ',
    'Payment Currency': 'สกุลเงินที่ชำระ',
    'Customer Payment Number': 'เลขที่ใบรับชำระ',
    'Show Payment Button': 'แสดงปุ่มชำระเงิน',
    'Cheque': 'เช็ค',
    'Cheque Date': 'วันที่เช็ค',
    'Cheque Number': 'เลขที่เช็ค',
    'Cheque Type': 'ประเภทเช็ค',
    'Payment Cheque': 'เช็คจ่าย',
    'Receipt Cheque': 'เช็ครับ',
    'Check Show': 'แสดงเช็ค',
    'Check Type Show': 'แสดงประเภทเช็ค',
    'AI Analysis length': 'ความยาวผลวิเคราะห์ AI',
    'AI Parsed Result (JSON)': 'ผลที่ AI อ่านได้ (JSON)',
    'AI Verified': 'AI ตรวจแล้ว',
    'Can Post Without AI': 'ยืนยันได้โดยไม่ต้องผ่าน AI',
    'Reset Keep AI Active': 'กลับเป็นร่างแบบคงผล AI',
    'Reset To Draft (Keep AI)': 'กลับเป็นร่าง (คงผล AI)',
    'Show Reset Draft Keep AI': 'แสดงปุ่มกลับเป็นร่าง (คงผล AI)',

    # --- ใบสำคัญ ---
    'Voucher': 'ใบสำคัญ',
    'Account Voucher': 'ใบสำคัญ',
    'Voucher Entries': 'รายการใบสำคัญ',
    'Voucher Lines': 'รายการในใบสำคัญ',
    'Voucher Statistics': 'สถิติใบสำคัญ',
    'Search Vouchers': 'ค้นหาใบสำคัญ',
    'Purchase Voucher': 'ใบสำคัญซื้อ',
    'Vendor Voucher': 'ใบสำคัญจ่าย',
    'Can Edit Voucher': 'แก้ไขใบสำคัญได้',

    # --- เงินทดรอง ---
    'Advance': 'เงินทดรอง',
    'Account Advance': 'เงินทดรองจ่าย',
    'Amount Advance': 'จำนวนเงินทดรอง',
    'Advance Account': 'บัญชีเงินทดรอง',
    'Advance Account Setting': 'ตั้งค่าบัญชีเงินทดรอง',
    'Advance Clear': 'เคลียร์เงินทดรอง',
    'Avance Clear': 'เคลียร์เงินทดรอง',
    'Clear Advance': 'เคลียร์เงินทดรอง',
    'Advance Information': 'ข้อมูลเงินทดรอง',
    'Advance Journal': 'สมุดบันทึกเงินทดรอง',
    'Advance Request': 'ขอเบิกเงินทดรอง',
    'Advance System': 'ระบบเงินทดรอง',
    'Advance Total': 'ยอดเงินทดรองรวม',
    'Reference Advance': 'อ้างอิงเงินทดรอง',
    'Clear': 'เคลียร์',
    'Clear Amount': 'ยอดเคลียร์',
    'Clear Tax': 'เคลียร์ภาษี',
    'Clear VAT': 'เคลียร์ภาษีมูลค่าเพิ่ม',
    'State Clear': 'สถานะการเคลียร์',
    'Due Date Clear': 'วันครบกำหนดเคลียร์',
    'Due Date Request': 'วันครบกำหนดตามคำขอ',
    'Partial Amount Clearing': 'ยอดเคลียร์บางส่วน',
    'Partial Clearing': 'เคลียร์บางส่วน',
    'Cash Bill Count': 'จำนวนบิลเงินสด',

    # --- ภาษี / ใบกำกับ ---
    'Tax': 'ภาษี',
    '% Tax': '% ภาษี',
    'Taxes': 'ภาษี',
    'Tax Amount': 'ยอดภาษี',
    'Tax Base': 'ฐานภาษี',
    'Base Amount': 'ยอดฐาน',
    'Tax Branch': 'สาขา (ภาษี)',
    'Tax Correction': 'ปรับปรุงภาษี',
    'Tax Form': 'แบบภาษี',
    'Tax Group': 'กลุ่มภาษี',
    'Tax Groups': 'กลุ่มภาษี',
    'Tax ID': 'เลขประจำตัวผู้เสียภาษี',
    'Vendor Tax ID': 'เลขประจำตัวผู้เสียภาษีของผู้ขาย',
    'Tax Line': 'รายการภาษี',
    'Tax Payer': 'ผู้ชำระภาษี',
    'Tax Rate (%)': 'อัตราภาษี (%)',
    'Tax Tags': 'แท็กภาษี',
    'Tax Accumulate': 'ภาษีสะสม',
    'Detail Taxes': 'รายละเอียดภาษี',
    'Keep Zero Line Taxes': 'เก็บรายการภาษีที่เป็นศูนย์',
    'Taxes must be included in price.': 'ราคาต้องรวมภาษีแล้ว',
    'Maximum Tax in Range': 'ภาษีสูงสุดในช่วง',
    'Originator Tax': 'ภาษีต้นทาง',
    'Tax Invoice': 'ใบกำกับภาษี',
    'Tax Invoices': 'ใบกำกับภาษี',
    'Tax Invoice Detail': 'รายละเอียดใบกำกับภาษี',
    'Tax Invoice Sequence': 'ลำดับเลขใบกำกับภาษี',
    'Customer Tax Invoice Number': 'เลขที่ใบกำกับภาษีขาย',
    'Customer Tax Invoice Number (Undue VAT)': 'เลขที่ใบกำกับภาษีขาย (ภาษียังไม่ถึงกำหนด)',
    'VAT': 'ภาษีมูลค่าเพิ่ม',
    'VAT Report': 'รายงานภาษีมูลค่าเพิ่ม',
    'VAT Report Options': 'ตัวเลือกรายงานภาษีมูลค่าเพิ่ม',
    'Thai Tax Report': 'รายงานภาษีไทย',
    'Thai Tax Reports': 'รายงานภาษีไทย',
    'Revenue Department': 'กรมสรรพากร',

    # --- หัก ณ ที่จ่าย / ภ.ง.ด. ---
    'WHT': 'หัก ณ ที่จ่าย',
    'Withholding': 'หัก ณ ที่จ่าย',
    'Withholding Tax': 'ภาษีหัก ณ ที่จ่าย',
    'Wht Tax': 'ภาษีหัก ณ ที่จ่าย',
    'WHT Amount': 'ยอดหัก ณ ที่จ่าย',
    'Withholding Amount': 'ยอดหัก ณ ที่จ่าย',
    'Withholding Tax Amount': 'ยอดภาษีหัก ณ ที่จ่าย',
    'Total Exclude WHT': 'ยอดรวมไม่รวมหัก ณ ที่จ่าย',
    'Withholding Tax Account': 'บัญชีภาษีหัก ณ ที่จ่าย',
    'Withholding Tax Rates': 'อัตราภาษีหัก ณ ที่จ่าย',
    'WHT Line': 'รายการหัก ณ ที่จ่าย',
    'Withholding Line': 'รายการหัก ณ ที่จ่าย',
    'Withholding Moves': 'รายการบันทึกหัก ณ ที่จ่าย',
    'Withholding Tax Move': 'รายการภาษีหัก ณ ที่จ่าย',
    'WHT Cert': 'หนังสือรับรองหัก ณ ที่จ่าย',
    'WHT Cert.': 'หนังสือรับรองหัก ณ ที่จ่าย',
    'WHT Certs': 'หนังสือรับรองหัก ณ ที่จ่าย',
    'WHT Certificates': 'หนังสือรับรองหัก ณ ที่จ่าย',
    'Withholding Tax Cert.': 'หนังสือรับรองหัก ณ ที่จ่าย',
    'Withholding Tax Certificate': 'หนังสือรับรองหัก ณ ที่จ่าย',
    '# Withholding Tax Certs': 'จำนวนหนังสือรับรองหัก ณ ที่จ่าย',
    'Ref WHT Cert.': 'อ้างอิงหนังสือรับรองหัก ณ ที่จ่าย',
    'Wht Cert Status': 'สถานะหนังสือรับรองหัก ณ ที่จ่าย',
    'WHT Not yet created': 'ยังไม่สร้างหนังสือรับรองหัก ณ ที่จ่าย',
    'Not yet created': 'ยังไม่สร้าง',
    '⇒ Create withholding tax cert.': '⇒ สร้างหนังสือรับรองหัก ณ ที่จ่าย',
    '⇒ Show withholding tax certs': '⇒ ดูหนังสือรับรองหัก ณ ที่จ่าย',
    'WHT Cert - Print Signature': 'หนังสือรับรองหัก ณ ที่จ่าย (พิมพ์ลายเซ็น)',
    'Preprint - Withholding Tax Cert Form': 'หนังสือรับรองหัก ณ ที่จ่าย (พิมพ์ลงแบบฟอร์ม)',
    'Company Vendor Withholding Tax': 'ภาษีหัก ณ ที่จ่าย ผู้ขายนิติบุคคล',
    'Individual Vendor Withholding Tax': 'ภาษีหัก ณ ที่จ่าย ผู้ขายบุคคลธรรมดา',
    'WHT Report': 'รายงานหัก ณ ที่จ่าย',
    'WHT Income Tax Report': 'รายงานภาษีหัก ณ ที่จ่าย (ภ.ง.ด.)',
    'Withholding Tax Report Options': 'ตัวเลือกรายงานภาษีหัก ณ ที่จ่าย',
    'WHT Report Format': 'รูปแบบรายงานหัก ณ ที่จ่าย',
    'Wht Report Format': 'รูปแบบรายงานหัก ณ ที่จ่าย',
    'Income': 'เงินได้',
    'Income Code': 'รหัสเงินได้',
    'Income Description': 'รายละเอียดเงินได้',
    'Income From (>)': 'เงินได้ตั้งแต่ (>)',
    'Income To (<=)': 'เงินได้ถึง (<=)',
    'Income Tax Form': 'แบบ ภ.ง.ด.',
    'Default Income Tax Form': 'แบบ ภ.ง.ด. เริ่มต้น',
    'Type of Income': 'ประเภทเงินได้',
    'Default Type of Income': 'ประเภทเงินได้เริ่มต้น',
    'WHT Income': 'เงินได้ที่หัก ณ ที่จ่าย',
    'WHT Income Code': 'รหัสเงินได้หัก ณ ที่จ่าย',
    'Paid Continuously': 'ออกให้ตลอดไป',
    'Paid One Time': 'ออกให้ครั้งเดียว',
    'PND1': 'ภ.ง.ด.1',
    'PND1A': 'ภ.ง.ด.1ก',
    'PND2': 'ภ.ง.ด.2',
    'PND3': 'ภ.ง.ด.3',
    'PND3a': 'ภ.ง.ด.3ก',
    'PND53': 'ภ.ง.ด.53',
    'Personal Income Tax': 'ภาษีเงินได้บุคคลธรรมดา',
    'Personal Income Tax Move': 'รายการภาษีเงินได้บุคคลธรรมดา',
    'PIT Move Monitoring': 'ติดตามรายการภาษีเงินได้บุคคลธรรมดา',
    'PIT Rate': 'อัตราภาษีเงินได้บุคคลธรรมดา',
    'PIT Rate Table': 'ตารางอัตราภาษีเงินได้บุคคลธรรมดา',

    # --- สินทรัพย์ ---
    'Assets': 'ทรัพย์สิน',
    'Asset Count': 'จำนวนทรัพย์สิน',
    'Asset From': 'ทรัพย์สินตั้งแต่',
    'Asset To': 'ทรัพย์สินถึง',
    'Asset Image': 'รูปทรัพย์สิน',
    'Asset Line': 'รายการทรัพย์สิน',
    'Asset Number Sequence': 'ลำดับเลขทรัพย์สิน',
    'Auto Asset Number by Sequence': 'รันเลขทรัพย์สินอัตโนมัติ',
    'Asset Profile': 'หมวดทรัพย์สิน',
    'Profile': 'หมวดทรัพย์สิน',
    'Asset Removal': 'ตัดจำหน่ายทรัพย์สิน',
    'Removed': 'ตัดจำหน่ายแล้ว',
    'Running': 'ใช้งานอยู่',
    'RUN': 'ใช้งานอยู่',
    'Init': 'ยอดยกมา',
    'Asset Condition Type': 'ประเภทสภาพทรัพย์สิน',
    'Asset Sub State All': 'สถานะย่อยทรัพย์สิน (ทั้งหมด)',
    'Asset Sub-Status': 'สถานะย่อยทรัพย์สิน',
    'sub.state Asset': 'สถานะย่อยทรัพย์สิน',
    'Assets analysis': 'วิเคราะห์ทรัพย์สิน',
    'Assets Analysis': 'วิเคราะห์ทรัพย์สิน',
    'Financial Assets': 'ทรัพย์สินถาวร',
    'Financial Assets report': 'รายงานทรัพย์สินถาวร',
    'Parent Asset': 'ทรัพย์สินหลัก',
    'Parent Asset Group': 'กลุ่มทรัพย์สินหลัก',
    'Search Asset Group': 'ค้นหากลุ่มทรัพย์สิน',
    'Include draft assets': 'รวมทรัพย์สินสถานะร่าง',
    'Create an asset by product item': 'สร้างทรัพย์สินแยกตามรายการสินค้า',
    'Accumulate missed depreciations': 'รวมค่าเสื่อมราคาที่ยังไม่ได้คิด',
    'Accumulation Method': 'วิธีสะสม',
    'Amount Already Depreciated': 'ค่าเสื่อมราคาที่คิดไปแล้ว',
    'Depreciation': 'ค่าเสื่อมราคา',
    'Depreciation Base': 'ฐานคิดค่าเสื่อมราคา',
    'Depreciation Date': 'วันที่คิดค่าเสื่อมราคา',
    'Depreciation Dates': 'วันที่คิดค่าเสื่อมราคา',
    'Depreciation Entry': 'รายการบันทึกค่าเสื่อมราคา',
    'Depreciation Method': 'วิธีคิดค่าเสื่อมราคา',
    'Depreciation Month': 'เดือนที่คิดค่าเสื่อมราคา',
    'Depreciation Name': 'ชื่อรายการค่าเสื่อมราคา',
    'Depreciation Rate (%)': 'อัตราค่าเสื่อมราคา (%)',
    'Next Period Depreciation': 'ค่าเสื่อมราคางวดถัดไป',
    'Number of Depreciations': 'จำนวนงวดค่าเสื่อมราคา',
    'Number of Years or end date': 'จำนวนปี หรือ วันที่สิ้นสุด',
    'Degressive': 'ลดลงตามอัตรา',
    'Degressive up to Salvage Value': 'ลดลงตามอัตรา จนถึงมูลค่าซาก',
    'Degressive Factor': 'ตัวคูณแบบลดลงตามอัตรา',
    'Degressive-Linear': 'ลดลงตามอัตรา-เส้นตรง',
    'Linear up to Salvage Value': 'เส้นตรง จนถึงมูลค่าซาก',
    'Salvage Type': 'ประเภทมูลค่าซาก',
    'Salvage Value': 'มูลค่าซาก',
    'Min-Value Account': 'บัญชีขาดทุนจากการจำหน่าย',
    'Plus-Value Account': 'บัญชีกำไรจากการจำหน่าย',
    'Residual Value Account': 'บัญชีมูลค่าคงเหลือ',
    'View Yearly Summary': 'ดูสรุปรายปี',
    'Yearly Report': 'รายงานรายปี',

    # --- รายงานการเงิน ---
    'Financial reports': 'รายงานการเงิน',
    'Thai Accounting Reports': 'รายงานบัญชีไทย',
    'Aged Partner Balance': 'รายงานอายุลูกหนี้/เจ้าหนี้',
    'General Ledger': 'บัญชีแยกประเภท',
    'Journal Ledger': 'รายงานสมุดบันทึก',
    'Open Items': 'รายการค้างชำระ',
    'Trial Balance': 'งบทดลอง',
    'Cash Flow Report': 'รายงานกระแสเงินสด',
    'Consolidated': 'รวมยอด',
    'Activate centralization': 'สรุปรวมยอดต่อบัญชี',
    'Disable account details expansion': 'ปิดการขยายรายละเอียดบัญชี',
    'Do not display parent levels': 'ไม่แสดงระดับบน',
    'Group entries by': 'จัดกลุ่มรายการตาม',
    'Sort entries by': 'เรียงรายการตาม',
    'Hide account ending balance at 0': 'ซ่อนบัญชีที่ยอดยกไปเป็น 0',
    'Hide accounts at 0': 'ซ่อนบัญชีที่ยอดเป็น 0',
    'Hierarchy Levels to display': 'จำนวนระดับที่แสดง',
    'Limit hierarchy levels': 'จำกัดจำนวนระดับ',
    'Show hierarchy': 'แสดงตามลำดับชั้น',
    'Show foreign currency': 'แสดงสกุลเงินต่างประเทศ',
    'Show Cancelled': 'แสดงรายการที่ยกเลิก',
    'Intervals configuration': 'ตั้งค่าช่วงอายุหนี้',
    'Display Columns Description': 'แสดงคำอธิบายคอลัมน์',
    'Last Reports Generated': 'รายงานที่สร้างล่าสุด',
    'MIS Report': 'รายงาน MIS',
    'MIS Reports': 'รายงาน MIS',
    'MIS Reporting': 'รายงาน MIS',
    'MIS Report Instance': 'รายงาน MIS',
    'MIS Report Style': 'รูปแบบรายงาน MIS',
    'MIS Report Styles': 'รูปแบบรายงาน MIS',
    'MIS Report Templates': 'แม่แบบรายงาน MIS',
    'Actuals': 'ยอดจริง',
    'Actuals (alternative)': 'ยอดจริง (แหล่งอื่น)',
    'Aggregate': 'วิธีรวมค่า',
    'Based On': 'คำนวณจาก',
    'Compare columns': 'เปรียบเทียบคอลัมน์',
    'Comparison Method': 'วิธีเปรียบเทียบ',
    'Comparison Mode': 'โหมดเปรียบเทียบ',
    'Sum columns': 'รวมคอลัมน์',
    "KPI's": 'ตัวชี้วัด (KPI)',
    'Sub KPI': 'ตัวชี้วัดย่อย',
    "Sub KPI's": 'ตัวชี้วัดย่อย',
    'Sub reports': 'รายงานย่อย',
    'Sub Reports': 'รายงานย่อย',
    'Subreport': 'รายงานย่อย',
    'Queries': 'คิวรี',
    'Style': 'รูปแบบ',
    'Style name': 'ชื่อรูปแบบ',
    'Background Color': 'สีพื้นหลัง',
    'Background Color Inherit': 'ใช้สีพื้นหลังตามแม่แบบ',
    'Color Inherit': 'ใช้สีตามแม่แบบ',
    'Divider Inherit': 'ใช้ตัวคั่นตามแม่แบบ',
    'Dp Inherit': 'ใช้ทศนิยมตามแม่แบบ',
    'Factor inherit': 'ใช้ตัวคูณตามแม่แบบ',
    'Font': 'แบบอักษร',
    'Font Size': 'ขนาดอักษร',
    'Font Size Inherit': 'ใช้ขนาดอักษรตามแม่แบบ',
    'Font Style': 'รูปแบบอักษร',
    'Font Style Inherit': 'ใช้รูปแบบอักษรตามแม่แบบ',
    'Font Weight': 'ความหนาอักษร',
    'Font Weight Inherit': 'ใช้ความหนาอักษรตามแม่แบบ',
    'Hide Always': 'ซ่อนเสมอ',
    'Hide Always Inherit': 'ใช้การซ่อนเสมอตามแม่แบบ',
    'Hide Empty': 'ซ่อนเมื่อว่าง',
    'Hide Empty Inherit': 'ใช้การซ่อนเมื่อว่างตามแม่แบบ',
    'Indent': 'ย่อหน้า',
    'Indent Level': 'ระดับย่อหน้า',
    'Indent Level Inherit': 'ใช้ระดับย่อหน้าตามแม่แบบ',
    'Prefix Inherit': 'ใช้คำนำหน้าตามแม่แบบ',
    'Suffix Inherit': 'ใช้คำต่อท้ายตามแม่แบบ',
    'Rounding inherit': 'ใช้การปัดเศษตามแม่แบบ',
    'Text color': 'สีข้อความ',
    'Header Text Color': 'สีข้อความหัวตาราง',
    'Bold': 'ตัวหนา',
    'Italic': 'ตัวเอียง',
    'large': 'ใหญ่',
    'medium': 'กลาง',
    'small': 'เล็ก',
    'x-large': 'ใหญ่มาก',
    'x-small': 'เล็กมาก',
    'xx-large': 'ใหญ่พิเศษ',
    'xx-small': 'เล็กพิเศษ',

    # --- ชื่อเมนูแอปอื่น (เมนูแปลทั้งระบบ) ---
    'Configuration': 'การกำหนดค่า',
    'Settings': 'การตั้งค่า',
    'Overview': 'ภาพรวม',
    'Inbox': 'กล่องข้อความ',
    'Quick Access': 'เข้าถึงด่วน',
    'My Dashboard': 'แดชบอร์ดของฉัน',
    'Dashboards': 'แดชบอร์ด',
    'Dashboard Manager': 'จัดการแดชบอร์ด',
    'Import Dashboard': 'นำเข้าแดชบอร์ด',
    'Import Dashboards': 'นำเข้าแดชบอร์ด',
    'Connect': 'เชื่อมต่อ',
    'Connect Spreadsheet': 'เชื่อมต่อสเปรดชีต',
    'Create Data Template': 'สร้างแม่แบบข้อมูล',
    'Credential': 'ข้อมูลรับรอง',
    'Authorization Scope': 'ขอบเขตการอนุญาต',
    'Scope': 'ขอบเขต',
    'Branches': 'สาขา',
    'Company Types': 'ประเภทบริษัท',
    'Operating Units': 'หน่วยปฏิบัติการ',
    'NPD Connection Settings': 'ตั้งค่าการเชื่อมต่อ NPD',
    'Date Ranges': 'ช่วงวันที่',
    'Date ranges': 'ช่วงวันที่',
    'Date Range Types': 'ประเภทช่วงวันที่',
    'Generate Date Ranges': 'สร้างช่วงวันที่',
    'Jasper Reports': 'รายงาน Jasper',
    'Order Lines': 'รายการสั่งขาย',
    'Sales Invoice Plan': 'แผนการออกใบแจ้งหนี้ขาย',
    'Sales Analysis By Products': 'วิเคราะห์ยอดขายตามสินค้า',
    'Sale Objective': 'วัตถุประสงค์การขาย',
    'Quotations Rent': 'ใบเสนอราคาเช่า',
    'Sales Orders Rent': 'คำสั่งเช่า',
    'Purchase Requests': 'ใบขอซื้อ',
    'Purchase Request Lines': 'รายการใบขอซื้อ',
    'Scrap Reason Codes': 'รหัสเหตุผลการตัดทิ้ง',
    'Moves Analysis': 'วิเคราะห์การเคลื่อนไหวสินค้า',
    'Stock Transfer': 'โอนย้ายสินค้า',
    # action ที่ตั้งชื่อเป็น xmlid ไว้ (เมนูรับ/โอนย้าย/ส่งสินค้า)
    'stock.method_action_picking_tree_incoming': 'การรับสินค้า',
    'stock.method_action_picking_tree_internal': 'การโอนย้ายภายใน',
    'stock.method_action_picking_tree_outgoing': 'การส่งสินค้า',
}

TH_TERMS = {norm(k): v for k, v in _RAW.items()}
