{
    "name": "Account Advance",
    "version": "18.0.1.0.0",
    "summary": "Employee Advance Payment Management",
    "description": "Manage employee advance requests, payments, and clearing",
    "category": "Accounting",
    "author": "Perfect Blending",
    "website": "https://www.perfectblending.com",
    "license": "AGPL-3",
    "depends": [
        "base",
        "account",
        "hr",
        "l10n_th_account_tax",
        "multi_branch_management_aagam",
    ],
    "data": [
        "data/ir_sequence_data.xml",
        "data/advance_security.xml",
        "security/ir.model.access.csv",
        "views/account_advance_request_view.xml",
        "views/account_advance_view.xml",
        "views/account_advance_clear_view.xml",
        "views/res_config_view.xml",
    ],
    "installable": True,
    "auto_install": False,
    "application": False,
}
